name: CI

on: [ push ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: use node 16.16
        uses: action/setup-node@v2
        with:
          node-version: 16.16.0
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: ./npm.bat run unit:test --info --stacktrace
